# Generated by Django 4.2.7 on 2023-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_author_book_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quote',
            field=models.CharField(max_length=200),
        ),
    ]
