# Generated by Django 4.2.7 on 2023-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_book_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='Books', to='testapp.author'),
        ),
    ]
